# Generated by Django 4.0 on 2022-01-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'loig_form',
                'verbose_name_plural': 'loig_forms',
            },
        ),
    ]
