# Generated by Django 4.0 on 2022-01-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Cidnumber', models.IntegerField()),
                ('Email', models.CharField(max_length=50, unique=True)),
                ('Phonenumber', models.IntegerField()),
                ('Licensenumber', models.IntegerField()),
            ],
            options={
                'verbose_name': 'register',
                'verbose_name_plural': 'registers',
            },
        ),
        migrations.DeleteModel(
            name='login_form',
        ),
    ]
